name: ReportPE
main: ReportPE\Main
api: 2.1.0
description: Add /report command, for cheater.
version: 1.0.0
author: CookieCode
commands:
    report:
        description: Report
permission:
    report.report.view:
        default: op
